name: Quality ratchet
on:
  pull_request:
    branches: ["main"]

jobs:
  line-count-check:
    name: Line count must increase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: tiernacity/ratchet@v0.1.0-alpha.5
        with:
          metric: "wc -l < content.txt"
          gt: main
